/**
 * Unit tests for the migration plan executor.
 *
 * No real systemd, no real docker, no real broker. Every side-effect
 * primitive is injected; we exercise happy path + forced-failure
 * rollback against a typed plan generated by `buildPlan`.
 */
import { describe, it, expect, beforeEach } from "vitest";
import {
  mkdtempSync,
  readFileSync,
  existsSync,
  writeFileSync,
  mkdirSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { buildPlan } from "./plan.js";
import { executePlan, type ExecutorDeps } from "./executor.js";
import { _resetLogChainForTests } from "./log.js";
import type { RunCommand } from "./preflight.js";

beforeEach(() => {
  _resetLogChainForTests();
});

function tmpRoot(): string {
  return mkdtempSync(join(tmpdir(), "sr-exec-"));
}

interface Recorded {
  cmd: string;
  args: readonly string[];
}

function makeRunner(
  fail?: (cmd: string, args: readonly string[]) => string | null,
): { run: RunCommand; calls: Recorded[] } {
  const calls: Recorded[] = [];
  const run: RunCommand = async (cmd, args) => {
    calls.push({ cmd, args });
    const errMsg = fail?.(cmd, args);
    if (errMsg) {
      return { stdout: "", stderr: errMsg, exitCode: 1 };
    }
    return { stdout: "", stderr: "", exitCode: 0 };
  };
  return { run, calls };
}

function readLog(path: string): Array<Record<string, unknown>> {
  if (!existsSync(path)) return [];
  return readFileSync(path, "utf8")
    .split("\n")
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l) as Record<string, unknown>);
}

function setupRoot(): { root: string; deps: Required<ExecutorDeps>["logPath"] | string } {
  const root = tmpRoot();
  return { root, deps: root };
}

describe("executePlan to-host", () => {
  it("happy path: stops compose, re-enables/starts systemd, marker=host", async () => {
    const root = tmpRoot();
    const logPath = join(root, "migration.log");
    const composePath = join(root, "compose", "docker-compose.yml");
    const runtimeModePath = join(root, "runtime-mode");
    const watchdogPausePath = join(root, "watchdog.paused");
    // Pretend we were in docker mode.
    mkdirSync(root, { recursive: true });
    writeFileSync(runtimeModePath, "docker\n", "utf8");
    // Pretend the compose file exists (so compose-down's existsSync
    // branch includes -f).
    mkdirSync(join(root, "compose"), { recursive: true });
    writeFileSync(composePath, "# stale compose\n", "utf8");

    const { run, calls } = makeRunner();

    const plan = buildPlan("to-host", {
      agents: ["alice", "bob"],
      composeProject: "switchroom-fleet",
      composePath,
    });

    const result = await executePlan(
      plan,
      { composeProject: "switchroom-fleet", composePath },
      {
        runCommand: run,
        generateComposeContent: () => "# unused for to-host\n",
        probeAgentBroker: async () => true,
        confirmUidAlign: async () => true,
        chownPath: async () => undefined,
        logPath,
        runtimeModePath,
        watchdogPausePath,
        agentsRoot: join(root, "agents"),
      },
    );

    expect(result.ok).toBe(true);
    expect(result.completed.length).toBe(plan.steps.length);
    expect(readFileSync(runtimeModePath, "utf8").trim()).toBe("host");
    expect(existsSync(watchdogPausePath)).toBe(false);

    const dockerDown = calls.find(
      (c) => c.cmd === "docker" && c.args.includes("down"),
    );
    expect(dockerDown).toBeTruthy();
    const enables = calls.filter(
      (c) => c.cmd === "systemctl" && c.args.includes("enable"),
    );
    expect(enables.length).toBe(2);
    const starts = calls.filter(
      (c) => c.cmd === "systemctl" && c.args.includes("start"),
    );
    expect(starts.length).toBe(2);

    const log = readLog(logPath);
    expect(log.length).toBe(plan.steps.length);
    expect(log.every((e) => e.status === "ok")).toBe(true);
    expect(log.every((e) => e.verb === "to-host")).toBe(true);
  });

  it("rolls back when systemd-start fails on second agent", async () => {
    const root = tmpRoot();
    const logPath = join(root, "migration.log");
    const composePath = join(root, "compose", "docker-compose.yml");
    const runtimeModePath = join(root, "runtime-mode");
    const watchdogPausePath = join(root, "watchdog.paused");
    writeFileSync(runtimeModePath, "docker\n", "utf8");

    let startCount = 0;
    const { run } = makeRunner((cmd, args) => {
      if (cmd === "systemctl" && args.includes("start")) {
        startCount++;
        if (startCount === 2) return "failed to start: unit not found";
      }
      return null;
    });

    const plan = buildPlan("to-host", {
      agents: ["alice", "bob"],
      composeProject: "switchroom-fleet",
      composePath,
    });

    const result = await executePlan(
      plan,
      { composeProject: "switchroom-fleet", composePath },
      {
        runCommand: run,
        generateComposeContent: () => "# stub\n",
        probeAgentBroker: async () => true,
        confirmUidAlign: async () => true,
        chownPath: async () => undefined,
        logPath,
        runtimeModePath,
        watchdogPausePath,
        agentsRoot: join(root, "agents"),
      },
    );

    expect(result.ok).toBe(false);
    expect(result.failed?.step.kind).toBe("systemd-start");
    // Marker must remain "docker" — marker-write hadn't run yet.
    expect(readFileSync(runtimeModePath, "utf8").trim()).toBe("docker");
  });
});

describe("executePlan to-docker", () => {
  it("happy path: runs all steps, writes ok log entries, exits ok", async () => {
    const root = tmpRoot();
    const logPath = join(root, "migration.log");
    const composePath = join(root, "compose", "docker-compose.yml");
    const runtimeModePath = join(root, "runtime-mode");
    const watchdogPausePath = join(root, "watchdog.paused");
    const agentsRoot = join(root, "agents");

    const { run, calls } = makeRunner();

    const plan = buildPlan("to-docker", {
      agents: ["alice"],
      composeProject: "switchroom-fleet",
      composePath,
    });

    const result = await executePlan(
      plan,
      {
        composeProject: "switchroom-fleet",
        composePath,
      },
      {
        runCommand: run,
        generateComposeContent: () => "# compose stub\n",
        probeAgentBroker: async () => true,
        confirmUidAlign: async () => true,
        chownPath: async () => undefined,
        logPath,
        runtimeModePath,
        watchdogPausePath,
        agentsRoot,
      },
    );

    expect(result.ok).toBe(true);
    expect(result.completed.length).toBe(plan.steps.length);

    // Sentinel was written then removed.
    expect(existsSync(watchdogPausePath)).toBe(false);

    // Marker reflects docker.
    expect(readFileSync(runtimeModePath, "utf8").trim()).toBe("docker");

    // Compose file was written.
    expect(readFileSync(composePath, "utf8")).toContain("compose stub");

    // systemctl + docker compose were invoked.
    const systemctl = calls.filter((c) => c.cmd === "systemctl");
    expect(systemctl.length).toBeGreaterThan(0);
    const dockerUp = calls.find(
      (c) => c.cmd === "docker" && c.args[0] === "compose" && c.args.includes("up"),
    );
    expect(dockerUp).toBeTruthy();

    // Every log entry has status=ok.
    const log = readLog(logPath);
    expect(log.length).toBe(plan.steps.length);
    expect(log.every((e) => e.status === "ok")).toBe(true);
    expect(log.every((e) => e.verb === "to-docker")).toBe(true);
  });

  it("rolls back when compose-up fails; runtime-mode stays unset", async () => {
    const root = tmpRoot();
    const logPath = join(root, "migration.log");
    const composePath = join(root, "compose", "docker-compose.yml");
    const runtimeModePath = join(root, "runtime-mode");
    const watchdogPausePath = join(root, "watchdog.paused");
    const agentsRoot = join(root, "agents");

    const { run } = makeRunner((cmd, args) => {
      if (cmd === "docker" && args[0] === "compose" && args.includes("up")) {
        return "port collision: 0.0.0.0:5432 already in use";
      }
      return null;
    });

    const plan = buildPlan("to-docker", {
      agents: ["alice"],
      composeProject: "switchroom-fleet",
      composePath,
    });

    const result = await executePlan(
      plan,
      { composeProject: "switchroom-fleet", composePath },
      {
        runCommand: run,
        generateComposeContent: () => "# compose stub\n",
        probeAgentBroker: async () => true,
        confirmUidAlign: async () => true,
        chownPath: async () => undefined,
        logPath,
        runtimeModePath,
        watchdogPausePath,
        agentsRoot,
      },
    );

    expect(result.ok).toBe(false);
    expect(result.failed?.step.kind).toBe("compose-up");
    expect(result.rolledBack.length).toBeGreaterThan(0);

    // Runtime-mode marker was never written (compose-up failed before
    // we got there) — should not exist.
    expect(existsSync(runtimeModePath)).toBe(false);

    // Compose file was unwound (rollback rm).
    expect(existsSync(composePath)).toBe(false);

    // Watchdog pause sentinel was unwound.
    expect(existsSync(watchdogPausePath)).toBe(false);

    // Log has at least one error and at least one rollback entry.
    const log = readLog(logPath);
    const statuses = log.map((e) => e.status);
    expect(statuses).toContain("error");
    expect(statuses).toContain("rollback");
  });

  it("vault-broker handshake failure triggers rollback", async () => {
    const root = tmpRoot();
    const logPath = join(root, "migration.log");
    const composePath = join(root, "compose", "docker-compose.yml");
    const runtimeModePath = join(root, "runtime-mode");
    const watchdogPausePath = join(root, "watchdog.paused");

    const { run } = makeRunner();

    const plan = buildPlan("to-docker", {
      agents: ["alice"],
      composeProject: "switchroom-fleet",
      composePath,
    });

    const result = await executePlan(
      plan,
      { composeProject: "switchroom-fleet", composePath },
      {
        runCommand: run,
        generateComposeContent: () => "# stub\n",
        probeAgentBroker: async () => false,
        confirmUidAlign: async () => true,
        chownPath: async () => undefined,
        logPath,
        runtimeModePath,
        watchdogPausePath,
        agentsRoot: join(root, "agents"),
      },
    );

    expect(result.ok).toBe(false);
    expect(result.failed?.step.kind).toBe("vault-broker-handshake");
    expect(existsSync(runtimeModePath)).toBe(false);
  });

  it("uid-align: skips when already aligned", async () => {
    const root = tmpRoot();
    const agentsRoot = join(root, "agents");
    mkdirSync(join(agentsRoot, "alice"), { recursive: true });

    let confirmCalled = false;
    let chownCalled = false;

    const { run } = makeRunner();
    const myUid = process.getuid?.() ?? 0;

    const plan = buildPlan("to-docker", {
      agents: ["alice"],
      composeProject: "switchroom-fleet",
      composePath: join(root, "c.yml"),
      targetUid: myUid, // already aligned to current process UID
    });

    const result = await executePlan(
      plan,
      { composeProject: "switchroom-fleet", composePath: join(root, "c.yml") },
      {
        runCommand: run,
        generateComposeContent: () => "# stub\n",
        probeAgentBroker: async () => true,
        confirmUidAlign: async () => {
          confirmCalled = true;
          return true;
        },
        chownPath: async () => {
          chownCalled = true;
        },
        logPath: join(root, "migration.log"),
        runtimeModePath: join(root, "runtime-mode"),
        watchdogPausePath: join(root, "watchdog.paused"),
        agentsRoot,
      },
    );

    expect(result.ok).toBe(true);
    expect(confirmCalled).toBe(false);
    expect(chownCalled).toBe(false);
  });

  it("uid-align: prompts and chowns when misaligned, refuses without consent", async () => {
    const root = tmpRoot();
    const agentsRoot = join(root, "agents");
    mkdirSync(join(agentsRoot, "alice"), { recursive: true });

    const { run } = makeRunner();
    const myUid = process.getuid?.() ?? 0;
    // Pretend the target is "myUid + 1" so the agent dir's actual UID
    // (== myUid) doesn't match. confirmUidAlign returns false → refusal.
    const plan = buildPlan("to-docker", {
      agents: ["alice"],
      composeProject: "switchroom-fleet",
      composePath: join(root, "c.yml"),
      targetUid: myUid + 1,
    });

    let confirmed = 0;
    const result = await executePlan(
      plan,
      { composeProject: "switchroom-fleet", composePath: join(root, "c.yml") },
      {
        runCommand: run,
        generateComposeContent: () => "# stub\n",
        probeAgentBroker: async () => true,
        confirmUidAlign: async () => {
          confirmed++;
          return false;
        },
        chownPath: async () => undefined,
        logPath: join(root, "migration.log"),
        runtimeModePath: join(root, "runtime-mode"),
        watchdogPausePath: join(root, "watchdog.paused"),
        agentsRoot,
      },
    );

    expect(result.ok).toBe(false);
    expect(result.failed?.step.kind).toBe("uid-align");
    expect(confirmed).toBe(1);
  });

  it("rollback log entries name the actual step they revert (not a shifted neighbour)", async () => {
    // Regression for the 3b-2b nit: with completed.length > rollback.length
    // (vault-broker-handshake / watchdog-resume push no hook), the previous
    // mapping `idx = completed[completed.length - 1 - h]` mis-attributed
    // rollback log entries. Force a failure AFTER the handshake step has
    // run (so completed includes a hook-less step) and assert every
    // rollback log entry references one of the steps that actually pushed
    // a hook — never the handshake/resume.
    const root = tmpRoot();
    const logPath = join(root, "migration.log");
    const composePath = join(root, "compose", "docker-compose.yml");
    const runtimeModePath = join(root, "runtime-mode");
    const watchdogPausePath = join(root, "watchdog.paused");

    // Two agents so we exercise multiple handshake steps.
    const plan = buildPlan("to-docker", {
      agents: ["alice", "bob"],
      composeProject: "switchroom-fleet",
      composePath,
    });

    // Find the marker-write index — failing it causes rollback after
    // both vault-broker-handshake steps already ran (they push no hook).
    const markerIdx = plan.steps.findIndex((s) => s.kind === "marker-write");
    expect(markerIdx).toBeGreaterThan(0);

    // We can't easily fail a marker-write via runCommand; instead, fail
    // a systemctl call indirectly by counting calls. Simpler: inject a
    // chownPath stub that never runs (no uid-align step, targetUid omitted).
    // To force a failure post-handshake, fail the broker probe for "bob"
    // only — that aborts at the second handshake AFTER alice's handshake
    // was a successful no-rollback step.
    let probeCount = 0;
    const { run } = makeRunner();
    const result = await executePlan(
      plan,
      { composeProject: "switchroom-fleet", composePath },
      {
        runCommand: run,
        generateComposeContent: () => "# stub\n",
        probeAgentBroker: async (agent) => {
          probeCount++;
          return agent !== "bob"; // fail on bob
        },
        confirmUidAlign: async () => true,
        chownPath: async () => undefined,
        logPath,
        runtimeModePath,
        watchdogPausePath,
        agentsRoot: join(root, "agents"),
      },
    );

    expect(result.ok).toBe(false);
    expect(result.failed?.step.kind).toBe("vault-broker-handshake");
    expect(probeCount).toBe(2);

    const log = readLog(logPath);
    const rollbackEntries = log.filter((e) => e.status === "rollback");
    expect(rollbackEntries.length).toBeGreaterThan(0);
    // No rollback entry should be tagged as a handshake or watchdog-resume
    // (those steps push no hook). Every rollback entry MUST correspond to
    // a step that actually had a rollback hook.
    for (const entry of rollbackEntries) {
      const stepLabel = String(entry.step);
      expect(stepLabel).not.toMatch(/vault-broker-handshake/);
      expect(stepLabel).not.toBe("watchdog-resume");
      // And it should match one of: watchdog-pause, systemd-stop,
      // systemd-disable, compose-generate, compose-up, marker-write,
      // uid-align.
      expect(stepLabel).toMatch(
        /^(watchdog-pause|systemd-(stop|disable|enable|start)|compose-(generate|up|down)|marker-write|uid-align)/,
      );
    }
  });

  it("preserves prior runtime-mode marker on rollback", async () => {
    const root = tmpRoot();
    const runtimeModePath = join(root, "runtime-mode");
    mkdirSync(root, { recursive: true });
    writeFileSync(runtimeModePath, "host\n", "utf8");

    const composePath = join(root, "c.yml");
    // Force final-step (vault-broker-handshake) failure AFTER marker-write
    // would have run? marker-write happens AFTER handshake in the plan
    // order, so we instead force the marker step itself by failing
    // *after* it completes. The simplest test here: confirm that on a
    // forced failure the marker rollback restores the prior content.
    // We force compose-up to fail; marker-write never runs, marker
    // stays "host".
    const { run } = makeRunner((cmd, args) => {
      if (cmd === "docker" && args.includes("up")) return "boom";
      return null;
    });

    const plan = buildPlan("to-docker", {
      agents: ["alice"],
      composeProject: "switchroom-fleet",
      composePath,
    });

    const result = await executePlan(
      plan,
      { composeProject: "switchroom-fleet", composePath },
      {
        runCommand: run,
        generateComposeContent: () => "# stub\n",
        probeAgentBroker: async () => true,
        confirmUidAlign: async () => true,
        chownPath: async () => undefined,
        logPath: join(root, "migration.log"),
        runtimeModePath,
        watchdogPausePath: join(root, "watchdog.paused"),
        agentsRoot: join(root, "agents"),
      },
    );

    expect(result.ok).toBe(false);
    expect(readFileSync(runtimeModePath, "utf8").trim()).toBe("host");
  });
});
