// AUTO-GENERATED by scripts/build.mjs — do not edit by hand.
// Tracked in git so `tsc --noEmit` works on a fresh clone before `npm run build`.
// Values are refreshed every time `npm run build` runs.

export const VERSION: string = "0.5.2";
export const COMMIT_SHA: string | null = "ec7f1015";
export const COMMIT_DATE: string | null = "2026-05-08T11:28:06+10:00";
export const LATEST_PR: number | null = 802;
export const COMMITS_AHEAD_OF_TAG: number | null = 14;
