// AUTO-GENERATED by scripts/build.mjs — do not edit by hand.
// Tracked in git so `tsc --noEmit` works on a fresh clone before `npm run build`.
// Values are refreshed every time `npm run build` runs.

export const VERSION: string = "0.10.0";
export const COMMIT_SHA: string | null = "6391f219";
export const COMMIT_DATE: string | null = "2026-05-15T14:39:34+10:00";
export const LATEST_PR: number | null = 1317;
export const COMMITS_AHEAD_OF_TAG: number | null = 24;
